# Generated by Django 5.0.6 on 2024-07-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ops', 'Operation User'), ('client', 'Client User')], max_length=10),
        ),
    ]
